### ISSUE TITLE
Checkpoints for 8-step models

### ISSUE THREAD

**Issue by lyx0208** [yandex-research/invertible-cd#3]
Thank you for your excellent work! I was wondering if you have any plans to release the checkpoints for the 8-step models. Thanks a lot in advance.

**Comment by quickjkee** [comment]
Hello, thanks for the question! In our work, we didn't consider 8-step models. We deal with 3- and 4-steps (4 forwards and 4 reverses, in total, 8 steps for inversion). We found this to be sufficient.

The 8-step model means 8 steps for generation and 16 steps for inversion, in our terms. Do you mean this?

**Comment by lyx0208** [comment]
So the "8 steps" in Figure 8 mean 4 forwards and 4 reverses? That make sense, thanks for your response!
