### ISSUE TITLE
Errors I met when running the training code on multi-GPUs

### ISSUE THREAD

**Issue by lyx0208** [yandex-research/invertible-cd#5]
Hello! I try to run the sh_scripts/run_sd15_lora.sh on multi-GPUs, by setting "--num_processes=4", and meet the following error:

[AW0701 03:52:22.574000 139785762685568 torch/distributed/elastic/multiprocessing/api.py:868] Unable to shutdown process 42346 via Signals.SIGHUP, forcefully exiting via Signals.SIGKILL
W0701 03:52:23.470000 139785762685568 torch/distributed/elastic/multiprocessing/api.py:868] Unable to shutdown process 42347 via Signals.SIGHUP, forcefully exiting via Signals.SIGKILL
W0701 03:52:23.960000 139785762685568 torch/distributed/elastic/multiprocessing/api.py:868] Unable to shutdown process 42348 via Signals.SIGHUP, forcefully exiting via Signals.SIGKILL
W0701 03:52:24.172000 139785762685568 torch/distributed/elastic/multiprocessing/api.py:868] Unable to shutdown process 42349 via Signals.SIGHUP, forcefully exiting via Signals.SIGKILL
torch.distributed.elastic.multiprocessing.api.SignalException: Process 42260 got signal: 1

This error appear several times on two of my machine, one 4*A100 and the other 4*L40S. Is there any possible reason that leads to this error?

**Comment by lyx0208** [comment]
Also, a small bug I found which doesn't worth another issue. That is, in the lines start from 992 in train_icd_sd15_lora.py, the codes only delete "checkpoint-X" dirs and left all the "forward-checkpoint-X".

**Comment by quickjkee** [comment]
I've just double-checked the training code. It works on my 8x A100 machine. At what point does this error occur? 
Could you try to increase CPU/RAM memory (probably it is not enough) and specify the device IDs with CUDA_VISIBLE_DEVICES=...

And could you check if you meet the same error when running these scripts?
https://github.com/luosiallen/latent-consistency-model/tree/main/LCM_Training_Script/consistency_distillation

**Comment by lyx0208** [comment]
@quickjkee. The error appears when I try running the code with "nohup" but it works properly when I use "tmux", but anyway it works. Thanks for your reply.
